

const actionType = {
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    FETCH_DATA_Q1_SUCCESS: 'FETCH_DATA_Q1_SUCCESS', 
    FETCH_DATA_Q2_SUCCESS: 'FETCH_DATA_Q2_SUCCESS',
    FETCH_DATA_Q3_SUCCESS: 'FETCH_DATA_Q3_SUCCESS',
    FETCH_FILTERED_COUNTRY: ' FETCH_FILTERED_COUNTRY',
    FETCH_SLOT_MACHINE: ' FETCH_SLOT_MACHINE',
    FETCH_DATA_FAILED: 'FETCH_DATA_FAILED'
}




export default actionType